import type { Metadata } from "next";
import { Josefin_Sans,Bebas_Neue,Monoton } from "next/font/google";

import "./globals.css";

const josefins = Josefin_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={josefins.className}>{children}</body>
    </html>
  );
}
